### ISSUE TITLE
Cannot change the name of the identifier column

### ISSUE THREAD

**Issue by kcmcleod** [lszeremeta/molstruct#1]
The identifier param is called `ID` when replacing the default column name *but* it is called `IDENTIFIER` when using it to create the JSON, rdfa etc.

I.e.,
```
if args.identifier or args.columns:
    ID = args.identifier
```

versus
```
        if row.get(IDENTIFIER):
            out_str += '  "identifier" : ' + json.dumps(row.get(IDENTIFIER)) + ',\n'
```

**Comment by lszeremeta** [comment]
Thank you for reporting this bug. Recently I have changed a lot in the code and I missed it.
Fixed in 65e6941
